name: Run tests with strace-

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    paths:
    - '*.py'
    - 'requirements.txt'
    - 'libretranslate/**'
    - '.github/workflows/run-tests.yml'

jobs:

  tests_python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y strace
        pipx install hatch
        hatch run locales

    - name: Test with pytest and strace
      run: |
        sudo strace -f -o strace_output.txt hatch run test
        cat strace_output.txt

    - name: Upload strace logs
      uses: actions/upload-artifact@v2
      with:
        name: strace-logs
        path: strace_output.txt

  test_docker_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Docker build with strace
        run: |
          sudo apt-get update
          sudo apt-get install -y strace
          sudo strace -f -o docker_build_strace.txt docker build -f docker/Dockerfile -t libretranslate .
          cat docker_build_strace.txt

      - name: Docker build with some models and strace
        run: |
          sudo strace -f -o docker_build_models_strace.txt docker build -f docker/Dockerfile -t libretranslate --build-arg models=en,es .
          cat docker_build_models_strace.txt

      - name: Upload Docker build strace logs
        uses: actions/upload-artifact@v4
        with:
          name: docker-build-strace-logs
          path: |
            docker_build_strace.txt
            docker_build_models_strace.txt
